---
slug: ultimate-docker-bootcamp
filename: ultimate-docker-bootcamp
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2018
uuid: 4dc724e8-3722-409d-b35f-51623f2a9416
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
